version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-26-alpha
  environment:
    TERM: dumb
    _JAVA_OPTIONS: "-Xms350m -Xmx1600m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

jobs:
  check:
    <<: *defaults
    steps:
      - checkout
      - run: git config diff.mnemonicprefix false

#Setup env
      - run:
          name: Install bundle
          command: gem install bundle

#Cache
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: gems-{{ checksum "Gemfile.lock" }}

#Run gradle tasks
      - run:
          name: Lint and detekt
          command: ./gradlew :app:check

      - store_artifacts:
          path: "app/build/reports"
          destination: reports

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
          destination: junit

      - persist_to_workspace:
          root: ~/code
          paths:
            - .

  reportToPullRequest:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - run:
          name: Run danger
          command: bundle exec danger

workflows:
    version: 2
    check_and_report:
      jobs:
        - check
        - reportToPullRequest:
            requires:
              - check